### ISSUE TITLE
GenCross.cna 

### ISSUE THREAD

**Issue by trickster0** [gloxec/CrossC2#12]
You forgot a semi-colon at line 37 of the .cna file at the end ;)

**Comment by trickster0** [comment]
Also maybe you should convert this for the 4th version of cobalt strike ;)

**Comment by gloxec** [comment]
Yes, there are plans for version 4.0. But so far the main work is still trying to implement some cool features for the Red Team. For example, CrossC2 in the form of a dynamic library, which can be injected into other processes without being displayed in `ps aux` (this has been implemented, but because of the dynamic generation of Payload for Mobile platforms, the issue has not yet been introduced). And the most important function at present, like the windows platform, you can load and execute the executable file ELF / MachO without files, or load and execute the `.so` / `.dylib` dynamic library.

**Comment by gloxec** [comment]
And like some native functions, such as portscan, screen capture, keyboard recording, etc., a named pipe will be reserved for third-party dynamic libraries to send execution results. In this way, third-party developers can write custom attack dynamic libraries (.so / .dylib) or executable file (.ELF / .MachO), use cna script to complete the execution without file landing.
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/5158011/77331933-5cd36c80-6d5c-11ea-864a-f24413b7a5f3.png">
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/5158011/77331981-6957c500-6d5c-11ea-9ecb-e813856ea205.png">

**Comment by trickster0** [comment]
I really like this project, keep it up :)
