### ISSUE TITLE
stageless  macos&linux not working on 4.4

### ISSUE THREAD

**Issue by bane2021** [gloxec/CrossC2#138]
I am trying to create reverse HTTPS listener  using the CrossC2 script but it fails with error 

```
C:/xx/genCrossC2.Win.exe y.y.y.y 3333 ./.cobaltstrike.beacon_keys null MacOS x64 mac321 stageless 4.4

                CrossC2 v3.0.2#dev  @hook
{cs = 4.1 ~ 4.4}
read keys error!
generate beacon keys error
*[error] : read key error
```

However the staged works.

When I try to use stageless on 4.3 instead it works like charm.

Am I missing something?

**Comment by gloxec** [comment]
This is because there are two versions of the CS4.4 version on the Internet.
One is to use new components (possibly from the Source version), you need to use `XXX ... Stageless 4.4` to parse Key.
The other is a traditional version of the CS component, so use the default to generate parameters, or use `xxx ... Stageless 4.3` can correctly parse Key.
Personally think that the second case is a reasonable CS version, and according to a large amount of feedback, it is basically useful with `Stageless 4.3` to complete the parsing, so subsequent versions will change the use parameters of CS4.4.
