### ISSUE TITLE
The file directory browser for linux beacon doesn't work well.

### ISSUE THREAD

**Issue by HellooTiger** [gloxec/CrossC2#69]
Every time a directory is clicked, a new path representing the directory is showed on top at the file directory browser on the left rather than  expand the directory at the clicked position. It's a little bit annoying.

**Comment by gloxec** [comment]
The problem is that cobaltstrike.jar is divided by the windows directory symbol `\` when drawing the UI interface. The problem cannot be changed directly unless cobaltstrike.jar is manually patched.
Similar to this problem, when opening a directory or performing any file operation, the `\` symbol will be forced to be added at the end, so that the path problem can only be forced to be repaired on the beacon side.

**Comment by HellooTiger** [comment]
Sure.
