### ISSUE TITLE
make beacon call home through a specific network interface.

### ISSUE THREAD

**Issue by HellooTiger** [gloxec/CrossC2#71]
In a linux system with multiple network interfaces, the default route rule does not make these application on the system reach Internet. One of these network interfaces, "eth2", can reach outside, which is confirmed by "ping -I eth2 xxxxx", however, the route on the "eth2 " has lower priority than the default gateway route. 

Is there a way to make the beacon call home just specifying the "eth2" interface? Using a "route add xxxxx" command could solve this issue, however this system-wide change may impact other running applications, which increases the possibility of being detected.

**Comment by gloxec** [comment]
setsockopt(socket , SOL_SOCKET , SO_BINDTODEVICE , "eth0" , strlen("eth0")+ 1 );

**Comment by gloxec** [comment]
Maybe you need to implement a loader, which is responsible for implementing what you said to detect available network interfaces. Then use `LD_PRELOAD` to start the beacon, so that you can hook the socket() function and set SO_BINDTODEVICE every time you create a socket to complete the package sending of the specified interface.

```
setsockopt(sock_raw, SOL_SOCKET, SO_BINDTODEVICE, "eth2", strlen("eth2")+ 1 );
```

**Comment by HellooTiger** [comment]
That's a brilliant idea! It worked! BTW, the detail of implementation is a little bit different than the answer above after exploring from Google.
 
snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "eth0");	
setsockopt(sockfd, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr, sizeof(ifr));
