### ISSUE TITLE
can't run the c2 in the PATH

### ISSUE THREAD

**Issue by jashfjsad** [gloxec/CrossC2#79]
after i copy the shell into /usr/bin folder like /usr/bin/shell,i can't run "shell" to start the shell; however ,/usr/bin/shell will get work ,i‘ve tried this on ubuntu 18.04 and centos7 
![shell](https://user-images.githubusercontent.com/82137032/115062662-9a032300-9eb8-11eb-9e6e-41b979b6d070.PNG)
gencrossc2 version 2.2.1

**Comment by gloxec** [comment]
After testing, this phenomenon is a realization problem of Linux daemon.
For example, when running /usr/bin/shell, the specific system call is:
```
execve("/usr/bin/shell", ["/usr/bin/shell"], [/* 28 vars */]) = 0
```
But if you put it in the PATH and call it again, it starts like this:
```
execve("/usr/bin/shell", ["shell"], [/* 28 vars */]) = 0
```
This problem will cause the subsequent fork operation at the bottom of the daemon to exit incorrectly because the `shell` file cannot be found.
```
set_robust_list(0x8c4d8c0, 0xc)         = 0
setsid()                                = 48377
time(NULL)                              = 1620686705
open("shell", O_RDONLY)                   = -1 ENOENT (No such file or directory)
exit_group(0)                           = ?
```

**Comment by gloxec** [comment]
The solution can only be to avoid using this strategy, or you can use the following tips:
```
cd /usr/bin/
shell
```
